# Generated by Django 5.2.7 on 2025-11-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_userupvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_views',
            field=models.IntegerField(default=0),
        ),
    ]
