# Generated by Django 5.2.7 on 2025-11-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_post_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
