# Generated by Django 5.2.7 on 2025-11-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('about', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('account_age', models.PositiveIntegerField(default=18)),
                ('gender', models.CharField(choices=[('Other', 'Other'), ('Male', 'Male'), ('Female', 'Female')], default='other', max_length=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
            ],
        ),
    ]
